### ISSUE TITLE
Any chance this could edit issue descriptions too?

### ISSUE THREAD

**Issue by tomwarner13** [codesoap/jirae#1]
Just installed the tool and I love it, very cool! But most of my frustration with being forced to use the WYSIWIG is in issue descriptions, where it's exponentially more annoying to not be able to edit as plaintext. Would it be possible to edit descriptions as well with this tool? I could also try and implement that myself if you'd be interested and submit a PR :)

**Comment by codesoap** [comment]
Glad to hear you find the tool useful :-)

Being able to also edit descriptions would be a very good addition and is already on my TODO list: https://github.com/codesoap/jirae/blob/f5ebe28dcd0ce4fa49f4761e247a04fe86d10cce/main.go#L62

I would probably implement it at some point in the future, but if you want to speed things up, a PR would be welcome! I would imagine something like adding a flag like `jirae -d SCO-1234`.

**Comment by codesoap** [comment]
Because of issue #3 the interface of jirae changed. Thus I would now not use a new `-d` flag, but just let jirae determine whether the passed URL is a comment or issue URL.

**Comment by codesoap** [comment]
Editing issue descriptions is now possible: https://github.com/codesoap/jirae/commit/e469c3b199a08dc1cb0c97d0b0d2f571d10ae870
