### ISSUE TITLE
Add Comments

### ISSUE THREAD

**Issue by tbussmann** [codesoap/jirae#4]
It would be great if `jirae` would be able to add comments to issues instead of only editing existing ones. The [API for this](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-comments/#api-rest-api-2-issue-issueidorkey-comment-post) seems to be straight forward, but some things needs to be worked out first:
* the interface to use. Currently passing a link to the issue itself edits its description, so we need a new clever syntax here.
* the interface may need to indicate the visibility of the comment (public / private) which may be tricky to do in a generic way using the `visibility` structure
* adding public comments does usually trigger notification emails to the issue's participants. Therefore, it would be nice if there was way to preview the rendered comment before. There seems to be way for [ADF](https://atlaskit.atlassian.com/examples.html?groupId=editor&packageId=renderer&exampleId=dac-viewer) but I'm not aware of something for the old-style syntax.

**Comment by codesoap** [comment]
Creating new comments is something I definitely want to add to `jirae`. I think I'll just add a flag like `-c`. I might find some time to implement this on Friday.

I have never changed any visibility settings of a comment before, so I didn't plan on making this a feature of `jirae`. Is this something you do often? Is this something "normal users" are even allowed to change?

Previewing a comment is outside the scope of what I want to do with `jirae`. I think this should be done with a different tool and might be integrated into the workflow with a script similar to the one you presented in #2.

**Comment by tbussmann** [comment]
> I have never changed any visibility settings of a comment before, so I didn't plan on making this a feature of jirae. Is this something you do often? Is this something "normal users" are even allowed to change?

Not sure how common this is, be we usually have internal (only visible to agents) and public (visible to customer) comments mixed in the cases. I investigated a bit futher:
* when reading comments the difference is indicated by `"jsdPublic": false`, however I wasn't able to write this field, directly ("Additional Properties") nor wrapped in `properties`
* I came across the specific [servicedesk API](https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-request/#api-rest-servicedeskapi-request-issueidorkey-comment-post) that exposes a `public` field alongside the `body` - didn't try that
* As a workaround using the current generic API, I found a hint that seem to work well in my tests: `"properties":[{ "key": "sd.public.comment", "value": { "internal":true } }]`
* the `visibiliy` field indeed seems to be something different with finer granularity

If you are interested in implementing this, the public / internal choice could either be made as command line parameter or in the interactive confirmation prompt.

**Comment by codesoap** [comment]
I have now added the ability to add comments through the `-c` flag in https://github.com/codesoap/jirae/commit/5a8fa222a69a7242e401e98b10909f6f68b0cbcc. This is contained in the release [0.4.0](https://github.com/codesoap/jirae/releases/tag/v0.4.0).

After reading your comment and taking a look at the visibility settings myself, I feel like I don't know enough about use cases to implement this well. I have, however, created the [fields Branch](https://github.com/codesoap/jirae/tree/fields) where I have added a `-f` flag, that can be used in combination with `-c`. You can give any additional fields, that you want to send with the request there; e.g.:
```
jirae -c -f '{"properties":[{"key": "sd.public.comment", "value": {"internal": true}}]}' 'https://somecorp.atlassian.net/browse/SCO-1234'
```

I'm interested to hear if this works for you.
